services:
  - type: web
    name: getkey-trg-anhkhoamods
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ADMIN_KEY
        sync: false
      - key: ADMIN_PANEL_PASSWORD
        sync: false
      - key: FLASK_SECRET
        sync: false
